# Generated by Django 4.2 on 2023-04-14 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('term', models.CharField(max_length=256)),
                ('script', models.CharField(max_length=12)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='SearchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=20)),
                ('data', models.JSONField(null=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.search')),
            ],
            options={
                'ordering': ['create_datetime'],
            },
        ),
    ]
