# Generated by Django 4.2 on 2023-04-14 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchcarprice_rename_searchstate_searchevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchWebShop',
            fields=[
                ('search_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.search')),
                ('search_string', models.CharField(max_length=256)),
                ('search_max_price', models.IntegerField()),
            ],
            bases=('search.search',),
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['create_datetime']},
        ),
        migrations.AlterModelOptions(
            name='searchcarprice',
            options={},
        ),
    ]
