# Generated by Django 4.2 on 2023-05-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_searchwebshop_alter_search_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='script',
            field=models.CharField(max_length=24),
        ),
    ]
