# Generated by Django 4.2 on 2023-05-31 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_search_script'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchevent',
            options={'ordering': ['created_datetime']},
        ),
        migrations.RenameField(
            model_name='searchevent',
            old_name='create_datetime',
            new_name='created_datetime',
        ),
    ]
