# Generated by Django 4.2 on 2023-05-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_searchevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='search_type',
            field=models.CharField(choices=[('one_time', 'Option once'), ('hourly', 'Option hourly'), ('daily', 'Option daily')], default='one_time', max_length=50),
            preserve_default=False,
        ),
    ]
